### ISSUE TITLE
Official Release Tag

### ISSUE THREAD

**Issue by pbui** [sethmlarson/rfc6555#4]
offlineimap 7.3.0 now requires rfc6555 and so I've packaged this module as part of an update to the offlineimap package for Void Linux:

https://github.com/void-linux/void-packages/pull/14207

Unfortunately, because rfc6555 does not have a release tagged on GitHub, it is not clear what version the archive on PyPI is (this is where the package is pulling the source code).  Moreover, while PyPI lists the version as 0.0.0 at the top of the page, it also lists 1.0.0 at the bottom of the page.

Would it be possible to get an official release tag here on GitHub and to clarify the release number of PyPI for clarity?  Thanks.

**Comment by sethmlarson** [comment]
The problem is I don't have a lot of time to spare to maintain all these libraries. :(
Would this be something you'd be willing to do? I can invite you as a collaborator.

**Comment by pbui** [comment]
@sethmlarson Thanks for offer, but I'm not a regular user of the library and therefore am not experienced enough with the code to maintain it (I'm simply packaging it because offlineimap requires it in the latest release).

In this particular case, we would just like a release tag on GitHub and a clarification of the version of the library.  I don't believe we would require much more than that (we don't need any ongoing work or additional maintenance).

**Comment by sethmlarson** [comment]
I've created a [0.1.0 release](https://github.com/sethmlarson/rfc6555/releases/tag/v0.1.0) with an actual tag on GitHub.
