### ISSUE TITLE
Issue with selectors2 dependency and python 3.10

### ISSUE THREAD

**Issue by rennefJ** [sethmlarson/rfc6555#6]
When importing rfc6555 in python 3.10 I get an error related to the selectors2 package used by rfc6555:

> import rfc6555
File "/usr/local/lib/python3.10/site-packages/rfc6555.py", line 19, in
from selectors2 import DefaultSelector, EVENT_WRITE
File "/usr/local/lib/python3.10/site-packages/selectors2.py", line 25, in
from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/init.py)

I wanted to open this issue in the selectors2 repository, but it is archived and no issues can be created anymore.
Searching the web for the error message I found this:
https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections
So it seems something changed from 3.9 to 3.10 that breaks selectors2

Would it be possible to fix the issue in rfc6555 by avoiding the need for selectors2? Or by including a fixed version of selectors2?

**Comment by sethmlarson** [comment]
The [latest release](https://github.com/sethmlarson/rfc6555/releases/tag/v0.1.0) now only uses `selectors2` for Python <3.5.

**Comment by rennefJ** [comment]
@sethmlarson thx a lot.
Tested today with python 3.10 in docker image (python:3-alpine) and offlineimap 8.0.0 and works.
